import React, { useState } from 'react';
import { FileText } from 'lucide-react';
import { FileUpload } from './components/FileUpload';
import { Summary } from './components/Summary';

function App() {
  const [fileName, setFileName] = useState<string>('');
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleFileUpload = async (file: File) => {
    setFileName(file.name);
    setLoading(true);
    
    // Simulate API call for PDF processing
    setTimeout(() => {
      setSummary("This is a sample summary of the uploaded PDF. In a real implementation, this would be generated by processing the PDF content through an AI model or API.");
      setLoading(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-white">
      <div className="container mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <div className="flex items-center justify-center mb-4">
            <FileText className="w-12 h-12 text-purple-600" />
          </div>
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            PDF Summary Generator
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Upload your PDF document and get an instant AI-powered summary. Perfect for quick document analysis and research.
          </p>
        </div>

        <div className="flex flex-col items-center justify-center space-y-8">
          <FileUpload onFileUpload={handleFileUpload} />
          <Summary 
            fileName={fileName}
            summary={summary}
            loading={loading}
          />
        </div>
      </div>
    </div>
  );
}

export default App;